# Generated by Django 5.2 on 2025-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(verbose_name='Kalorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.FloatField(verbose_name='Sacharidy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(verbose_name='Tuky'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(verbose_name='Bílkoviny'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('breakfast', 'Snídaně'), ('lunch', 'Oběd'), ('dinner', 'Večeře'), ('snack', 'Svačina'), ('any', 'Libovolné')], default='any', max_length=50, verbose_name='Typ jídla'),
        ),
    ]
