# Generated by Django 5.2 on 2025-09-21 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0002_alter_product_calories_alter_product_carbs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jidlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('type', models.CharField(choices=[('snidane', 'Snídaně'), ('obed', 'Oběd'), ('vecere', 'Večeře'), ('svacina', 'Svačina')], max_length=20)),
                ('ingredients', models.JSONField(default=list)),
                ('preparation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity',
            field=models.FloatField(help_text='Množství v gramech nebo porcích'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='jidlo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='kalkulacka.jidlo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
