# Generated by Django 5.2 on 2025-09-25 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0003_jidlo_remove_mealitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='g', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='jidlo',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='type',
            field=models.CharField(choices=[('snidane', 'Snídaně'), ('druhe_snidane', 'Druhá snídaně'), ('obed', 'Oběd'), ('svacina', 'Svačina'), ('vecere', 'Večeře')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalkulacka.ingredient')),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='kalkulacka.jidlo')),
            ],
        ),
    ]
