# Generated by Django 5.2 on 2025-09-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0004_ingredient_remove_jidlo_ingredients_alter_jidlo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='day',
            field=models.CharField(default='pondeli', max_length=20),
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='calories',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='carbs',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='fat',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='preparation',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='protein',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
