# Generated by Django 5.2 on 2025-09-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0005_ingredient_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('maso', 'Maso'), ('ryba', 'Ryby'), ('mlecne', 'Mléčné výrobky'), ('obiloviny', 'Obiloviny a kaše'), ('ovoce', 'Ovoce'), ('zelenina', 'Zelenina'), ('syry', 'Sýry'), ('tuky', 'Oleje a tuky'), ('ostatni', 'Ostatní')], default='ostatni', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.FloatField(),
        ),
    ]
