# Generated by Django 5.2 on 2025-10-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0006_ingredient_category_alter_ingredient_carbs_per_100g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='type',
            field=models.CharField(default='obed', max_length=20),
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='type',
            field=models.CharField(choices=[('snidane', 'Snídaně'), ('druhe_snidane', 'Druhá snídaně'), ('obed', 'Oběd'), ('svacina', 'Svačina'), ('vecere', 'Večeře')], max_length=20),
        ),
    ]
