# Generated by Django 5.2 on 2025-10-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0007_mealitem_type_alter_jidlo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(default='g', max_length=20),
        ),
    ]
