# Generated by Django 5.2 on 2025-10-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0008_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
