# Generated by Django 5.2 on 2025-10-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0009_mealplan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jidlo',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='jidla/'),
        ),
    ]
