# Generated by Django 5.2 on 2025-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0010_jidlo_obrazek'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='jidlo',
            name='type',
            field=models.CharField(choices=[('snidane', 'Snídaně'), ('druhe_snidane', 'Druhá snídaně'), ('obed', 'Oběd'), ('svacina', 'Svačina'), ('vecere', 'Večeře'), ('snack_extra', 'Extra snack')], max_length=20),
        ),
    ]
