# Generated by Django 5.2 on 2025-11-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0011_ingredient_price_100g_jidlo_price_alter_jidlo_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price_100g',
            new_name='price',
        ),
    ]
