# Generated by Django 5.2 on 2025-12-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulacka', '0016_alter_profile_user_alter_progressrecord_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jidlo',
            name='obrazek',
        ),
        migrations.AddField(
            model_name='jidlo',
            name='obrazek_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
